### PR TITLE
include cn translation

### PR DESCRIPTION
**Pull request by qbig**

### CODE REVIEW

**Comment by qbig** [comment]
@paul-schaaf ser

**Comment by paul-schaaf** [comment]
awesome!

could you add the link to the `anchor-book` commit to the introduction of the book itself as well? Many people won't read the readme.

**Comment by qbig** [comment]
@paul-schaaf done

**Review by polarisiota — APPROVED** [review]
非常好，就算我已经读过英文版的，读完你写的中文版之后对于Anchor有了更深入的理解。

**Comment by qbig** [comment]
@paul-schaaf could take a look?

**Comment by qbig** [comment]
@paul-schaaf ser

**Pull request closed without merging**
